from django.db import models

# Create your models here.
class Greeting(models.Model):
    when = models.DateTimeField('date created', auto_now_add=True)
    
class Specs(models.Model):
    brand = models.CharField(max_length=200)
    handset_color = models.CharField(max_length=200)
    form = models.CharField(max_length=200)
    call_features = models.CharField(max_length=200)
    model_name = models.CharField(max_length=200)
    touch_screen = models.CharField(max_length=200)
    sim_type = models.CharField(max_length=200)
    model_id = models.CharField(max_length=200)
    in_the_box = models.CharField(max_length=200)
    video_recording = models.CharField(max_length=200)
    secondary_camera = models.CharField(max_length=200)
    primary_camera = models.IntegerField(blank=True, null=True)
    video_player = models.CharField(max_length=200)
    music_player = models.CharField(max_length=200)
    fm = models.CharField(max_length=200)
    audio_jack = models.CharField(max_length=200)
    preinstalled_browser = models.CharField(max_length=200)
    bluetooth = models.CharField(max_length=200)
    internet_features = models.CharField(max_length=200)
    wifi = models.CharField(max_length=200)
    usb_connectivity = models.CharField(max_length=200)
    tethering = models.CharField(max_length=200)
    threeg = models.CharField(max_length=200)
    sensors = models.CharField(max_length=200)
    phone_book_memory = models.CharField(max_length=200)
    call_memory = models.CharField(max_length=200)
    sms_memory = models.CharField(max_length=200)
    sar_value = models.CharField(max_length=200)
    important_apps = models.CharField(max_length=200)
    additional_features = models.CharField(max_length=200)
    resolution = models.CharField(max_length=200)
    other_display_features = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    size = models.CharField(max_length=200)
    color = models.CharField(max_length=200)
    warranty_summary = models.CharField(max_length=200)
    talk_time = models.CharField(max_length=200)
    standby_time = models.CharField(max_length=200)
    expandable_memory = models.CharField(max_length=200)
    memory = models.CharField(max_length=200)
    internal = models.CharField(max_length=200)
    operating_freq = models.CharField(max_length=200)
    os = models.CharField(max_length=200)
    processor = models.CharField(max_length=200)
    other_camera_features = models.CharField(max_length=200)
    wap = models.CharField(max_length=200)
    gprs = models.CharField(max_length=200)
    weight = models.CharField(max_length=200)
    sim_size = models.CharField(max_length=200)
    hd_recording = models.CharField(max_length=200)
    business_features = models.CharField(max_length=200)
    zoom = models.CharField(max_length=200)
    navigation_technology = models.CharField(max_length=200)
    edge = models.CharField(max_length=200)
    user_memory = models.CharField(max_length=200)
    user_interface = models.CharField(max_length=200)
    sound_enhancement = models.CharField(max_length=200)
    dlna = models.CharField(max_length=200)
    charging_point = models.CharField(max_length=200)
    graphics = models.CharField(max_length=200)
    flash = models.CharField(max_length=200)
    nfc = models.CharField(max_length=200)
    keypad = models.CharField(max_length=200)
    ringtone = models.CharField(max_length=200)
    hdmi_port = models.CharField(max_length=200)
    java = models.CharField(max_length=200)
    covered_in_warranty = models.CharField(max_length=200)
    warranty_service_type = models.CharField(max_length=200)
    not_covered_in_warranty = models.CharField(max_length=200)
    type_1 = models.CharField(max_length=200)
    size_1 = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    price = models.IntegerField(blank=True, null=True)
    avail = models.IntegerField(blank=True, null=True)
    cpupwr = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'specs'
